/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * ArchiGenTN API
 * API de generation de plans architecturaux pour le marche tunisien. Genere des plans, exporte en DXF (AutoCAD) et effectue des analyses structurelles.
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  AnalyzePlanParams,
  GenerateAndAnalyzeParams,
  PlanGenerateRequest,
  PlanResponse
} from '../../models';





/**
 * Genere un plan a partir des exigences (terrain, pieces, reglementations). Retourne les pieces positionnees avec portes, fenetres et metriques. Le JSON de reponse peut etre reutilise directement dans /export/dxf et /analyze.
 * @summary Generer un plan architectural
 */
export type generatePlanResponse200 = {
  data: Blob
  status: 200
}

export type generatePlanResponse400 = {
  data: Blob
  status: 400
}
    
export type generatePlanResponseSuccess = (generatePlanResponse200) & {
  headers: Headers;
};
export type generatePlanResponseError = (generatePlanResponse400) & {
  headers: Headers;
};

export type generatePlanResponse = (generatePlanResponseSuccess | generatePlanResponseError)

export const getGeneratePlanUrl = () => {


  

  return `/api/plans/generate`
}

export const generatePlan = async (planGenerateRequest: PlanGenerateRequest, options?: RequestInit): Promise<generatePlanResponse> => {
  
  const res = await fetch(getGeneratePlanUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      planGenerateRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: generatePlanResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as generatePlanResponse
}




export const getGeneratePlanMutationOptions = <TError = Blob,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof generatePlan>>, TError,{data: PlanGenerateRequest}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof generatePlan>>, TError,{data: PlanGenerateRequest}, TContext> => {

const mutationKey = ['generatePlan'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof generatePlan>>, {data: PlanGenerateRequest}> = (props) => {
          const {data} = props ?? {};

          return  generatePlan(data,fetchOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type GeneratePlanMutationResult = NonNullable<Awaited<ReturnType<typeof generatePlan>>>
    export type GeneratePlanMutationBody = PlanGenerateRequest
    export type GeneratePlanMutationError = Blob

    /**
 * @summary Generer un plan architectural
 */
export const useGeneratePlan = <TError = Blob,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof generatePlan>>, TError,{data: PlanGenerateRequest}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof generatePlan>>,
        TError,
        {data: PlanGenerateRequest},
        TContext
      > => {
      return useMutation(getGeneratePlanMutationOptions(options), queryClient);
    }
    /**
 * Combine /generate et /export/dxf en un seul appel. Prend les exigences et retourne directement le fichier DXF.
 * @summary Generer un plan ET exporter directement en DXF
 */
export type generateAndExportDxfResponse200 = {
  data: Blob
  status: 200
}
    
export type generateAndExportDxfResponseSuccess = (generateAndExportDxfResponse200) & {
  headers: Headers;
};
;

export type generateAndExportDxfResponse = (generateAndExportDxfResponseSuccess)

export const getGenerateAndExportDxfUrl = () => {


  

  return `/api/plans/generate-dxf`
}

export const generateAndExportDxf = async (planGenerateRequest: PlanGenerateRequest, options?: RequestInit): Promise<generateAndExportDxfResponse> => {
  
  const res = await fetch(getGenerateAndExportDxfUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      planGenerateRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: generateAndExportDxfResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as generateAndExportDxfResponse
}




export const getGenerateAndExportDxfMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof generateAndExportDxf>>, TError,{data: PlanGenerateRequest}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof generateAndExportDxf>>, TError,{data: PlanGenerateRequest}, TContext> => {

const mutationKey = ['generateAndExportDxf'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof generateAndExportDxf>>, {data: PlanGenerateRequest}> = (props) => {
          const {data} = props ?? {};

          return  generateAndExportDxf(data,fetchOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type GenerateAndExportDxfMutationResult = NonNullable<Awaited<ReturnType<typeof generateAndExportDxf>>>
    export type GenerateAndExportDxfMutationBody = PlanGenerateRequest
    export type GenerateAndExportDxfMutationError = unknown

    /**
 * @summary Generer un plan ET exporter directement en DXF
 */
export const useGenerateAndExportDxf = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof generateAndExportDxf>>, TError,{data: PlanGenerateRequest}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof generateAndExportDxf>>,
        TError,
        {data: PlanGenerateRequest},
        TContext
      > => {
      return useMutation(getGenerateAndExportDxfMutationOptions(options), queryClient);
    }
    /**
 * Combine /generate et /analyze. Retourne le plan genere + le rapport structurel.
 * @summary Generer un plan ET analyser sa structure
 */
export type generateAndAnalyzeResponse200 = {
  data: Blob
  status: 200
}
    
export type generateAndAnalyzeResponseSuccess = (generateAndAnalyzeResponse200) & {
  headers: Headers;
};
;

export type generateAndAnalyzeResponse = (generateAndAnalyzeResponseSuccess)

export const getGenerateAndAnalyzeUrl = (params?: GenerateAndAnalyzeParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/plans/generate-and-analyze?${stringifiedParams}` : `/api/plans/generate-and-analyze`
}

export const generateAndAnalyze = async (planGenerateRequest: PlanGenerateRequest,
    params?: GenerateAndAnalyzeParams, options?: RequestInit): Promise<generateAndAnalyzeResponse> => {
  
  const res = await fetch(getGenerateAndAnalyzeUrl(params),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      planGenerateRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: generateAndAnalyzeResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as generateAndAnalyzeResponse
}




export const getGenerateAndAnalyzeMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof generateAndAnalyze>>, TError,{data: PlanGenerateRequest;params?: GenerateAndAnalyzeParams}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof generateAndAnalyze>>, TError,{data: PlanGenerateRequest;params?: GenerateAndAnalyzeParams}, TContext> => {

const mutationKey = ['generateAndAnalyze'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof generateAndAnalyze>>, {data: PlanGenerateRequest;params?: GenerateAndAnalyzeParams}> = (props) => {
          const {data,params} = props ?? {};

          return  generateAndAnalyze(data,params,fetchOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type GenerateAndAnalyzeMutationResult = NonNullable<Awaited<ReturnType<typeof generateAndAnalyze>>>
    export type GenerateAndAnalyzeMutationBody = PlanGenerateRequest
    export type GenerateAndAnalyzeMutationError = unknown

    /**
 * @summary Generer un plan ET analyser sa structure
 */
export const useGenerateAndAnalyze = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof generateAndAnalyze>>, TError,{data: PlanGenerateRequest;params?: GenerateAndAnalyzeParams}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof generateAndAnalyze>>,
        TError,
        {data: PlanGenerateRequest;params?: GenerateAndAnalyzeParams},
        TContext
      > => {
      return useMutation(getGenerateAndAnalyzeMutationOptions(options), queryClient);
    }
    /**
 * Prend un plan (JSON de PlanResponse) et genere un fichier DXF telechareable. Le DXF est compatible AutoCAD, LibreCAD, DraftSight. Utilisez la reponse de /generate comme input.
 * @summary Exporter un plan en DXF (AutoCAD)
 */
export type exportDxfResponse200 = {
  data: Blob
  status: 200
}

export type exportDxfResponse400 = {
  data: Blob
  status: 400
}
    
export type exportDxfResponseSuccess = (exportDxfResponse200) & {
  headers: Headers;
};
export type exportDxfResponseError = (exportDxfResponse400) & {
  headers: Headers;
};

export type exportDxfResponse = (exportDxfResponseSuccess | exportDxfResponseError)

export const getExportDxfUrl = () => {


  

  return `/api/plans/export/dxf`
}

export const exportDxf = async (planResponse: PlanResponse, options?: RequestInit): Promise<exportDxfResponse> => {
  
  const res = await fetch(getExportDxfUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      planResponse,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: exportDxfResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as exportDxfResponse
}




export const getExportDxfMutationOptions = <TError = Blob,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof exportDxf>>, TError,{data: PlanResponse}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof exportDxf>>, TError,{data: PlanResponse}, TContext> => {

const mutationKey = ['exportDxf'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof exportDxf>>, {data: PlanResponse}> = (props) => {
          const {data} = props ?? {};

          return  exportDxf(data,fetchOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type ExportDxfMutationResult = NonNullable<Awaited<ReturnType<typeof exportDxf>>>
    export type ExportDxfMutationBody = PlanResponse
    export type ExportDxfMutationError = Blob

    /**
 * @summary Exporter un plan en DXF (AutoCAD)
 */
export const useExportDxf = <TError = Blob,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof exportDxf>>, TError,{data: PlanResponse}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof exportDxf>>,
        TError,
        {data: PlanResponse},
        TContext
      > => {
      return useMutation(getExportDxfMutationOptions(options), queryClient);
    }
    /**
 * Effectue un pre-dimensionnement structurel (poutres BA) selon les normes tunisiennes. Verifie les portees, fleches et efforts pour chaque piece. Utilisez la reponse de /generate comme input.
 * @summary Analyse structurelle d'un plan
 */
export type analyzePlanResponse200 = {
  data: Blob
  status: 200
}
    
export type analyzePlanResponseSuccess = (analyzePlanResponse200) & {
  headers: Headers;
};
;

export type analyzePlanResponse = (analyzePlanResponseSuccess)

export const getAnalyzePlanUrl = (params?: AnalyzePlanParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/plans/analyze?${stringifiedParams}` : `/api/plans/analyze`
}

export const analyzePlan = async (planResponse: PlanResponse,
    params?: AnalyzePlanParams, options?: RequestInit): Promise<analyzePlanResponse> => {
  
  const res = await fetch(getAnalyzePlanUrl(params),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      planResponse,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: analyzePlanResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as analyzePlanResponse
}




export const getAnalyzePlanMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof analyzePlan>>, TError,{data: PlanResponse;params?: AnalyzePlanParams}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof analyzePlan>>, TError,{data: PlanResponse;params?: AnalyzePlanParams}, TContext> => {

const mutationKey = ['analyzePlan'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof analyzePlan>>, {data: PlanResponse;params?: AnalyzePlanParams}> = (props) => {
          const {data,params} = props ?? {};

          return  analyzePlan(data,params,fetchOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type AnalyzePlanMutationResult = NonNullable<Awaited<ReturnType<typeof analyzePlan>>>
    export type AnalyzePlanMutationBody = PlanResponse
    export type AnalyzePlanMutationError = unknown

    /**
 * @summary Analyse structurelle d'un plan
 */
export const useAnalyzePlan = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof analyzePlan>>, TError,{data: PlanResponse;params?: AnalyzePlanParams}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof analyzePlan>>,
        TError,
        {data: PlanResponse;params?: AnalyzePlanParams},
        TContext
      > => {
      return useMutation(getAnalyzePlanMutationOptions(options), queryClient);
    }
    