/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * ArchiGenTN API
 * API de generation de plans architecturaux pour le marche tunisien. Genere des plans, exporte en DXF (AutoCAD) et effectue des analyses structurelles.
 * OpenAPI spec version: 0.1.0
 */
import type { DoorDtoOrientation } from './doorDtoOrientation';

/**
 * Porte positionnee dans le plan
 */
export interface DoorDto {
  /** Position X en metres */
  x?: number;
  /** Position Y en metres */
  y?: number;
  /** Largeur de la porte en metres (standard TN: 0.90m interieur, 1.00m principale) */
  width?: number;
  /** Orientation */
  orientation?: DoorDtoOrientation;
}
