/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * ArchiGenTN API
 * API de generation de plans architecturaux pour le marche tunisien. Genere des plans, exporte en DXF (AutoCAD) et effectue des analyses structurelles.
 * OpenAPI spec version: 0.1.0
 */
import type { PlanResponse } from './planResponse';
import type { StructuralAnalysisResponse } from './structuralAnalysisResponse';

/**
 * Reponse combinee: plan genere + analyse structurelle
 */
export interface GenerateAndAnalyzeResponse {
  /** Plan architectural genere */
  plan?: PlanResponse;
  /** Rapport d'analyse structurelle */
  analysis?: StructuralAnalysisResponse;
}
