/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * ArchiGenTN API
 * API de generation de plans architecturaux pour le marche tunisien. Genere des plans, exporte en DXF (AutoCAD) et effectue des analyses structurelles.
 * OpenAPI spec version: 0.1.0
 */

/**
 * Metriques calculees du plan
 */
export interface PlanMetricsDto {
  /** Surface totale construite en m2 */
  totalArea?: number;
  /** COS calcule (surface batie / surface terrain) */
  cos?: number;
  /** CUF calcule (surface plancher / surface terrain) */
  cuf?: number;
  /** Conformite aux reglementations */
  regulationsCompliant?: boolean;
  /** Message si non conforme */
  complianceMessage?: string;
}
