/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * ArchiGenTN API
 * API de generation de plans architecturaux pour le marche tunisien. Genere des plans, exporte en DXF (AutoCAD) et effectue des analyses structurelles.
 * OpenAPI spec version: 0.1.0
 */
import type { RegulationsDto } from './regulationsDto';
import type { RequirementsDto } from './requirementsDto';
import type { TerrainDto } from './terrainDto';

/**
 * Requete de generation de plan architectural
 */
export interface PlanGenerateRequest {
  /** Dimensions du terrain */
  terrain: TerrainDto;
  /** Exigences du plan (pieces, style) */
  requirements: RequirementsDto;
  /** Reglementations urbanistiques (defaut: standard tunisien) */
  regulations?: RegulationsDto;
}
