/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * ArchiGenTN API
 * API de generation de plans architecturaux pour le marche tunisien. Genere des plans, exporte en DXF (AutoCAD) et effectue des analyses structurelles.
 * OpenAPI spec version: 0.1.0
 */
import type { DoorDto } from './doorDto';
import type { PlanMetricsDto } from './planMetricsDto';
import type { RoomDto } from './roomDto';
import type { TerrainDto } from './terrainDto';
import type { WindowDto } from './windowDto';

/**
 * Plan architectural genere (sert aussi d'input pour export DXF et analyse structurelle)
 */
export interface PlanResponse {
  /** Dimensions du terrain */
  terrain?: TerrainDto;
  /** Pieces positionnees dans le plan */
  rooms?: RoomDto[];
  /** Portes positionnees */
  doors?: DoorDto[];
  /** Fenetres positionnees */
  windows?: WindowDto[];
  /** Epaisseur des murs en metres (standard TN: 0.20m) */
  wallThickness?: number;
  /** Metriques calculees */
  metrics?: PlanMetricsDto;
}
