/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * ArchiGenTN API
 * API de generation de plans architecturaux pour le marche tunisien. Genere des plans, exporte en DXF (AutoCAD) et effectue des analyses structurelles.
 * OpenAPI spec version: 0.1.0
 */

/**
 * Reglementations urbanistiques tunisiennes (PAU)
 */
export interface RegulationsDto {
  /** Coefficient d'Occupation du Sol max */
  cos?: number;
  /** Coefficient d'Utilisation Fonciere max */
  cuf?: number;
  /** Retrait frontal minimum en metres */
  retraitFrontal?: number;
  /** Retrait lateral minimum en metres */
  retraitLateral?: number;
  /** Retrait arriere minimum en metres */
  retraitArriere?: number;
  /** Hauteur maximale du batiment en metres */
  hauteurMax?: number;
}
