/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * ArchiGenTN API
 * API de generation de plans architecturaux pour le marche tunisien. Genere des plans, exporte en DXF (AutoCAD) et effectue des analyses structurelles.
 * OpenAPI spec version: 0.1.0
 */

/**
 * Style architectural
 */
export type RequirementsDtoStyle = typeof RequirementsDtoStyle[keyof typeof RequirementsDtoStyle];


export const RequirementsDtoStyle = {
  moderne: 'moderne',
  traditionnel: 'traditionnel',
  neo_mauresque: 'neo_mauresque',
  colonial: 'colonial',
  mediterraneen: 'mediterraneen',
} as const;
