/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * ArchiGenTN API
 * API de generation de plans architecturaux pour le marche tunisien. Genere des plans, exporte en DXF (AutoCAD) et effectue des analyses structurelles.
 * OpenAPI spec version: 0.1.0
 */
import type { RequirementsDtoStyle } from './requirementsDtoStyle';
import type { RoomRequirementDto } from './roomRequirementDto';

/**
 * Exigences du plan architectural
 */
export interface RequirementsDto {
  /** Surface totale souhaitee en m2 */
  totalArea?: number;
  /** Nombre d'etages */
  floors?: number;
  /**
   * Liste des pieces souhaitees
   * @minItems 1
   */
  rooms: RoomRequirementDto[];
  /** Style architectural */
  style?: RequirementsDtoStyle;
}
