/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * ArchiGenTN API
 * API de generation de plans architecturaux pour le marche tunisien. Genere des plans, exporte en DXF (AutoCAD) et effectue des analyses structurelles.
 * OpenAPI spec version: 0.1.0
 */

/**
 * Type de piece
 * @minLength 1
 */
export type RoomRequirementDtoType = typeof RoomRequirementDtoType[keyof typeof RoomRequirementDtoType];


export const RoomRequirementDtoType = {
  salon: 'salon',
  chambre: 'chambre',
  cuisine: 'cuisine',
  sdb: 'sdb',
  wc: 'wc',
  entree: 'entree',
  couloir: 'couloir',
  bureau: 'bureau',
  garage: 'garage',
} as const;
