/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * ArchiGenTN API
 * API de generation de plans architecturaux pour le marche tunisien. Genere des plans, exporte en DXF (AutoCAD) et effectue des analyses structurelles.
 * OpenAPI spec version: 0.1.0
 */
import type { RoomRequirementDtoType } from './roomRequirementDtoType';

/**
 * Exigence pour une piece
 */
export interface RoomRequirementDto {
  /**
   * Type de piece
   * @minLength 1
   */
  type: RoomRequirementDtoType;
  /** Nom personnalise de la piece */
  name?: string;
  /**
   * Surface minimale souhaitee en m2
   * @minimum 1.5
   */
  minArea?: number;
  /** Nombre de pieces de ce type */
  count?: number;
}
