/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * ArchiGenTN API
 * API de generation de plans architecturaux pour le marche tunisien. Genere des plans, exporte en DXF (AutoCAD) et effectue des analyses structurelles.
 * OpenAPI spec version: 0.1.0
 */

/**
 * Piece positionnee dans le plan
 */
export interface RoomDto {
  /**
   * Nom de la piece
   * @minLength 1
   */
  name: string;
  /**
   * Type de piece
   * @minLength 1
   */
  type: string;
  /** Position X (coin inferieur gauche) en metres */
  x: number;
  /** Position Y (coin inferieur gauche) en metres */
  y: number;
  /** Largeur de la piece en metres */
  width: number;
  /** Hauteur (profondeur) de la piece en metres */
  height: number;
}
