/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * ArchiGenTN API
 * API de generation de plans architecturaux pour le marche tunisien. Genere des plans, exporte en DXF (AutoCAD) et effectue des analyses structurelles.
 * OpenAPI spec version: 0.1.0
 */

/**
 * Resultat d'analyse structurelle pour un element
 */
export interface StructuralElementResultDto {
  /** Type d'element (poutre, poteau, dalle) */
  elementType?: string;
  /** Identifiant de l'element */
  elementId?: string;
  /** Portee en metres */
  portee?: number;
  /** Moment flechissant max en kN.m */
  momentMax?: number;
  /** Effort tranchant max en kN */
  effortTranchant?: number;
  /** Fleche maximale calculee en mm */
  flecheMax?: number;
  /** Fleche admissible (L/500) en mm */
  flecheAdmissible?: number;
  /** Hauteur de poutre recommandee en metres */
  hauteurRecommandee?: number;
  /** Element conforme */
  valid?: boolean;
  /** Message de diagnostic */
  message?: string;
}
