/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * ArchiGenTN API
 * API de generation de plans architecturaux pour le marche tunisien. Genere des plans, exporte en DXF (AutoCAD) et effectue des analyses structurelles.
 * OpenAPI spec version: 0.1.0
 */
import type { StructuralElementResultDto } from './structuralElementResultDto';

/**
 * Rapport d'analyse structurelle
 */
export interface StructuralAnalysisResponse {
  /** Type de batiment */
  buildingType?: string;
  /** Charge totale appliquee en kN/m2 */
  chargeTotale?: number;
  /** Resultats par element structurel */
  elements?: StructuralElementResultDto[];
  /** Structure globalement conforme */
  globalValid?: boolean;
  /** Resume de l'analyse */
  summary?: string;
}
