/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * ArchiGenTN API
 * API de generation de plans architecturaux pour le marche tunisien. Genere des plans, exporte en DXF (AutoCAD) et effectue des analyses structurelles.
 * OpenAPI spec version: 0.1.0
 */

/**
 * Dimensions du terrain
 */
export interface TerrainDto {
  /**
   * Largeur du terrain en metres
   * @minimum 5
   */
  width: number;
  /**
   * Profondeur du terrain en metres
   * @minimum 5
   */
  height: number;
}
