/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * ArchiGenTN API
 * API de generation de plans architecturaux pour le marche tunisien. Genere des plans, exporte en DXF (AutoCAD) et effectue des analyses structurelles.
 * OpenAPI spec version: 0.1.0
 */

/**
 * Orientation
 */
export type WindowDtoOrientation = typeof WindowDtoOrientation[keyof typeof WindowDtoOrientation];


export const WindowDtoOrientation = {
  horizontal: 'horizontal',
  vertical: 'vertical',
} as const;
