/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * ArchiGenTN API
 * API de generation de plans architecturaux pour le marche tunisien. Genere des plans, exporte en DXF (AutoCAD) et effectue des analyses structurelles.
 * OpenAPI spec version: 0.1.0
 */
import type { WindowDtoOrientation } from './windowDtoOrientation';

/**
 * Fenetre positionnee dans le plan
 */
export interface WindowDto {
  /** Position X en metres */
  x?: number;
  /** Position Y en metres */
  y?: number;
  /** Largeur de la fenetre en metres */
  width?: number;
  /** Orientation */
  orientation?: WindowDtoOrientation;
}
