/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * ArchiGenTN API
 * API de generation de plans architecturaux pour le marche tunisien. Genere des plans, exporte en DXF (AutoCAD) et effectue des analyses structurelles.
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  GenerateAndAnalyze1Params,
  PlanGenerateRequest,
  PlanResponse
} from '../../models';





/**
 * Utilise Claude AI pour generer un plan architectural intelligent. Si l'API key est absente ou en cas d'erreur, retombe sur l'algorithme classique. Retourne le meme format PlanResponse, compatible avec /export/dxf et /analyze.
 * @summary Generer un plan via Claude AI
 */
export type generatePlan1Response200 = {
  data: Blob
  status: 200
}

export type generatePlan1Response400 = {
  data: Blob
  status: 400
}
    
export type generatePlan1ResponseSuccess = (generatePlan1Response200) & {
  headers: Headers;
};
export type generatePlan1ResponseError = (generatePlan1Response400) & {
  headers: Headers;
};

export type generatePlan1Response = (generatePlan1ResponseSuccess | generatePlan1ResponseError)

export const getGeneratePlan1Url = () => {


  

  return `http://localhost:8080/api/plans/ai/generate`
}

export const generatePlan1 = async (planGenerateRequest: PlanGenerateRequest, options?: RequestInit): Promise<generatePlan1Response> => {
  
  const res = await fetch(getGeneratePlan1Url(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      planGenerateRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: generatePlan1Response['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as generatePlan1Response
}




export const getGeneratePlan1MutationOptions = <TError = Blob,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof generatePlan1>>, TError,{data: PlanGenerateRequest}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof generatePlan1>>, TError,{data: PlanGenerateRequest}, TContext> => {

const mutationKey = ['generatePlan1'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof generatePlan1>>, {data: PlanGenerateRequest}> = (props) => {
          const {data} = props ?? {};

          return  generatePlan1(data,fetchOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type GeneratePlan1MutationResult = NonNullable<Awaited<ReturnType<typeof generatePlan1>>>
    export type GeneratePlan1MutationBody = PlanGenerateRequest
    export type GeneratePlan1MutationError = Blob

    /**
 * @summary Generer un plan via Claude AI
 */
export const useGeneratePlan1 = <TError = Blob,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof generatePlan1>>, TError,{data: PlanGenerateRequest}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof generatePlan1>>,
        TError,
        {data: PlanGenerateRequest},
        TContext
      > => {
      return useMutation(getGeneratePlan1MutationOptions(options), queryClient);
    }
    /**
 * Combine generation AI et export DXF en un seul appel. Retourne directement le fichier DXF.
 * @summary Generer un plan IA ET exporter en DXF
 */
export type generateAndExportDxf1Response200 = {
  data: Blob
  status: 200
}
    
export type generateAndExportDxf1ResponseSuccess = (generateAndExportDxf1Response200) & {
  headers: Headers;
};
;

export type generateAndExportDxf1Response = (generateAndExportDxf1ResponseSuccess)

export const getGenerateAndExportDxf1Url = () => {


  

  return `http://localhost:8080/api/plans/ai/generate-dxf`
}

export const generateAndExportDxf1 = async (planGenerateRequest: PlanGenerateRequest, options?: RequestInit): Promise<generateAndExportDxf1Response> => {
  
  const res = await fetch(getGenerateAndExportDxf1Url(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      planGenerateRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: generateAndExportDxf1Response['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as generateAndExportDxf1Response
}




export const getGenerateAndExportDxf1MutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof generateAndExportDxf1>>, TError,{data: PlanGenerateRequest}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof generateAndExportDxf1>>, TError,{data: PlanGenerateRequest}, TContext> => {

const mutationKey = ['generateAndExportDxf1'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof generateAndExportDxf1>>, {data: PlanGenerateRequest}> = (props) => {
          const {data} = props ?? {};

          return  generateAndExportDxf1(data,fetchOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type GenerateAndExportDxf1MutationResult = NonNullable<Awaited<ReturnType<typeof generateAndExportDxf1>>>
    export type GenerateAndExportDxf1MutationBody = PlanGenerateRequest
    export type GenerateAndExportDxf1MutationError = unknown

    /**
 * @summary Generer un plan IA ET exporter en DXF
 */
export const useGenerateAndExportDxf1 = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof generateAndExportDxf1>>, TError,{data: PlanGenerateRequest}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof generateAndExportDxf1>>,
        TError,
        {data: PlanGenerateRequest},
        TContext
      > => {
      return useMutation(getGenerateAndExportDxf1MutationOptions(options), queryClient);
    }
    /**
 * Combine generation AI et analyse structurelle. Retourne le plan genere + le rapport structurel.
 * @summary Generer un plan IA ET analyser sa structure
 */
export type generateAndAnalyze1Response200 = {
  data: Blob
  status: 200
}
    
export type generateAndAnalyze1ResponseSuccess = (generateAndAnalyze1Response200) & {
  headers: Headers;
};
;

export type generateAndAnalyze1Response = (generateAndAnalyze1ResponseSuccess)

export const getGenerateAndAnalyze1Url = (params?: GenerateAndAnalyze1Params,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `http://localhost:8080/api/plans/ai/generate-and-analyze?${stringifiedParams}` : `http://localhost:8080/api/plans/ai/generate-and-analyze`
}

export const generateAndAnalyze1 = async (planGenerateRequest: PlanGenerateRequest,
    params?: GenerateAndAnalyze1Params, options?: RequestInit): Promise<generateAndAnalyze1Response> => {
  
  const res = await fetch(getGenerateAndAnalyze1Url(params),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      planGenerateRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: generateAndAnalyze1Response['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as generateAndAnalyze1Response
}




export const getGenerateAndAnalyze1MutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof generateAndAnalyze1>>, TError,{data: PlanGenerateRequest;params?: GenerateAndAnalyze1Params}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof generateAndAnalyze1>>, TError,{data: PlanGenerateRequest;params?: GenerateAndAnalyze1Params}, TContext> => {

const mutationKey = ['generateAndAnalyze1'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof generateAndAnalyze1>>, {data: PlanGenerateRequest;params?: GenerateAndAnalyze1Params}> = (props) => {
          const {data,params} = props ?? {};

          return  generateAndAnalyze1(data,params,fetchOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type GenerateAndAnalyze1MutationResult = NonNullable<Awaited<ReturnType<typeof generateAndAnalyze1>>>
    export type GenerateAndAnalyze1MutationBody = PlanGenerateRequest
    export type GenerateAndAnalyze1MutationError = unknown

    /**
 * @summary Generer un plan IA ET analyser sa structure
 */
export const useGenerateAndAnalyze1 = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof generateAndAnalyze1>>, TError,{data: PlanGenerateRequest;params?: GenerateAndAnalyze1Params}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof generateAndAnalyze1>>,
        TError,
        {data: PlanGenerateRequest;params?: GenerateAndAnalyze1Params},
        TContext
      > => {
      return useMutation(getGenerateAndAnalyze1MutationOptions(options), queryClient);
    }
    